version: "3.9"

services:
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_todo_list
      MYSQL_USER: user
      MYSQL_PASSWORD: pass123
      MYSQL_ROOT_HOST: '%'
      TZ: 'America/Sao_Paulo'  # Configuração do fuso horário para Belo Horizonte
    volumes:
      - mysql-data:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - db-todo-list
    restart: always

networks:
  db-todo-list:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "111.111.10.0/24"

volumes:
  mysql-data:
    driver: local
